export const GET_ALL = 'GET_ALL';
export const DELETE = 'DELETE';
export const UPDATE = 'UPDATE';
export const GET_ALL_SERVICES_TO_ADD = 'GASTA'
export const PUSH_COMPANY_TO_REDUX='pctr';
export const REGISTER_SERVICE_FOR_COMPANY='rsfc';
export const ERROR_EXISTED_SERVICE_REGISTRATION='eesr';
export const GET_COMPANIES_FOR_REGISTRATION_BY_NAME = 'gcfrbn';
export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_SERVICES_BY_NAME = "GET_SERVICES_BY_NAME";